[package]
name = "zkmatrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.8.0"
# rust-gmp = "0.5"
hex = "0.4"
# rand = "0.8.4"
# rug = "1.14.0"

[dependencies.curv-kzen]
version = "0.8"
default-features = false
features = ["num-bigint"]
# lazy_static = "1.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = true
path = "benches/my_benchmark.rs"
